### ISSUE TITLE
Example input binding not working

### ISSUE THREAD

**Issue by 2005m** [massmutual/dcr#8]
Hi, 
The example input_binding doesn't seem to be working. I only see a data table but no charts. Is it me or is there a bug?

Also does the package support sunbust graphs like on dc.js website?

Thank you.

**Comment by XiangdongGu** [comment]
do you mean shiny::runGitHub("massmutual/dcr", subdir = "inst/example/input_binding")

I just tried, it works fine with me. Maybe you reinstall the package?

**Comment by XiangdongGu** [comment]
The sunburst chart should be easily produce, however it needs newer version of javascript libraries, I made a new branch that updates the versions, however there is minor issues for lineChart and I am still figuring out. The code to generate the chart is simple

First install the branch with newer js versions

```
devtools::install_github("massmutual/dcr", ref = "new_js_version")
```

Then make the charts
```
library(tidyverse)
library(dcr)
data <- read_csv("https://raw.githubusercontent.com/dc-js/dc.js/master/web/examples/morley.csv")

mydcr <- dcr(data)

chart3 <- dcrchart("rowChart", "test3", "Expt", reduceSum("Speed"), 200, 200)

chart2 <- dcrchart("rowChart", "test2",  "Run", reduceSum("Speed"), 200, 200)

chart <- dcrchart("sunburstChart", "test", c("Expt", "Run"), reduceSum("Speed"),
                  768, 480, innerRadius = 100)

mydcr + chart3 + chart2 + chart
```

<img width="645" alt="screen shot 2018-08-02 at 10 43 39 am" src="https://user-images.githubusercontent.com/5375417/43561259-d7d33c54-9648-11e8-9330-5019e0f6da8e.png">

**Comment by 2005m** [comment]
When I run the input_binding example I get something like the below image.
when I read your code I see that there are 3 other charts : pie-chart, line-chart and row-chart. But these are not displayed and I don't have any error message. FYI, I am running R 3.4.4 with shiny 1.1.0 and dplyr 0.7.6 on windows.

![image](https://user-images.githubusercontent.com/25661020/43589402-83f41a54-9666-11e8-84a4-94663f60a73c.png)

**Comment by 2005m** [comment]
Regarding the sunburst chart, it is working. Thank you very much for that.

**Comment by XiangdongGu** [comment]
I just fixed a few issues due to d3.js version upgrade (looks like a lot of incompatibility causing all the issues).  Can you try again?

First update new version
```
devtools:::install_github("massmutual/dcr", ref = "js_new_version")
```

Then

```
shiny::runGitHub("massmutual/dcr", subdir = "inst/example/input_binding")
```

<img width="1191" alt="screen shot 2018-08-04 at 12 29 38 am" src="https://user-images.githubusercontent.com/5375417/43654354-8b4b0e8a-977d-11e8-9212-632b444fa502.png">

**Comment by 2005m** [comment]
Still not working. I have tried on 2 different computers and also with the latest version of R (3.5.1).

**Comment by 2005m** [comment]
It is working. Thank you.
